In [45]:
#exercise1
import numpy as np 
x = np.array([1,2,3])
y = np.array([4,5,6])
result= x+y 
print(result)
print(x*3)
print(x**2)


[5 7 9]
[3 6 9]
[1 4 9]


In [ ]:
#exercise2 

z = np.array([1,4,9,16,25])
result = np.sqrt(z)
print(result)

[1. 2. 3. 4. 5.]


In [8]:
angles= np.array([0, np.pi/2, np.pi])
sine = np.sin(angles)
print(sine)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
#exercise3
matrix = np.arange(1,10).reshape(3,3)
vector = np.array([10,20,30])
summary = matrix + vector
print(summary)
#so the shapes of the matrix and vector arrays are 3,3 and 3, . the shape of vector is padded, for mathcing dimensions of both arrays
array = np.array([100,200])
#array + vector operation will give us an error cus their shapes arent matching

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [28]:
#exercise4 
data = np.empty((3,5))
summary = np.sum(data)
print(summary)
print(np.mean(data))
print(np.max(data))
second_summary = np.sum(data, axis = 0)
print(second_summary)
print(np.mean(data, axis = 1))



6.8101966266123e-310
4.5401310844083e-311
6.8101966266123e-310
[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 6.81019663e-310]
[0.00000000e+000 0.00000000e+000 1.36203933e-310]


In [35]:
#Reshaping arrays-Exercise 5 
arr = np.arange(12)
arr1 = arr.reshape((3,4))
arr2 = arr1.reshape((4,3))
arr3 = arr2.reshape((2,2,3)) 
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [40]:
#Exercise 6
m1= np.array([[1,2,3]])
m2 = np.array([[4,5,6]])
m3 = np.hstack((m1,m2))
m4 = np.vstack((m1,m2))
print(m3)
print(m4)


[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]


In [44]:
#Advanced Opeartions- Ex7
nums = np.arange(-5,5)
positive_numbers = nums > 0
print(nums[positive_numbers])

[1 2 3 4]


In [53]:
#Ex8
v1 = np.array([1,2,3]) 
v2  = np.array([4,5,6])
print(np.dot(v1,v2))
mat1 = np.full((2,2), 9)
mat2 = np.full((2,2), 7)
mat1 @ mat2
print(np.dot(mat1, mat2))

32
[[126 126]
 [126 126]]
