In [2]:
import numpy as np 
l = [1,2,3,4,5]
arr_1= np.array(l)
arr_1

array([1, 2, 3, 4, 5])

In [3]:
#2
nested_list = [[1,2,3], [4,5,6]]
arr_2 = np.array(nested_list)
arr_2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr_3 = np.zeros(10)
arr_3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr_4 = np.full((3,4),1)
arr_4

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
#5
arr_5 = np.arange(0,9)
arr_5



array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#6 
arr_6 = np.linspace(0,2,5)


In [20]:
array  = np.random.randint(0,100,9)
matrix = array.reshape(3, 3)
matrix


array([[93, 69, 99],
       [ 8, 88, 34],
       [77, 62, 55]], dtype=int32)

In [23]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)


(3, 3)
2
9


In [24]:
print(matrix.dtype)

int32


In [26]:
#exercise 3
array1= np.arange(10,19)
print(array1)
print(array1[3])
print(array1[2:5])
b = np.arange(0,16).reshape(4,4)
print(b)
print(b[0][2])
print(b[0:2, 2:]) #first two rows and last two columns
print(b[3:]) #last third column


[10 11 12 13 14 15 16 17 18]
13
[12 13 14]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2
[[2 3]
 [6 7]]
[[12 13 14 15]]
